config/routes.rb
Rails.application.routes.draw do
  resources :ponies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pony.rb
class Pony < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  before_action :set_pony, only: [:show, :edit, :update, :destroy]

  # GET /ponies
  # GET /ponies.json
  def index
    @ponies = Pony.all
  end

  # GET /ponies/1
  # GET /ponies/1.json
  def show
  end

  # GET /ponies/new
  def new
    @pony = Pony.new
  end

  # GET /ponies/1/edit
  def edit
  end

  # POST /ponies
  # POST /ponies.json
  def create
    @pony = Pony.new(pony_params)

    respond_to do |format|
      if @pony.save
        format.html { redirect_to @pony, notice: 'Pony was successfully created.' }
        format.json { render :show, status: :created, location: @pony }
      else
        format.html { render :new }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponies/1
  # PATCH/PUT /ponies/1.json
  def update
    respond_to do |format|
      if @pony.update(pony_params)
        format.html { redirect_to @pony, notice: 'Pony was successfully updated.' }
        format.json { render :show, status: :ok, location: @pony }
      else
        format.html { render :edit }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponies/1
  # DELETE /ponies/1.json
  def destroy
    @pony.destroy
    respond_to do |format|
      format.html { redirect_to ponies_url, notice: 'Pony was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pony
      @pony = Pony.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pony_params
      params.require(:pony).permit(:name, :profession, :cutie_mark)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ponies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ponies/_form.html.erb
<%= form_for(pony) do |f| %>
  <% if pony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pony.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
      <% pony.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :profession %>
    <%= f.text_field :profession %>
  </div>

  <div class="field">
    <%= f.label :cutie_mark %>
    <%= f.text_field :cutie_mark %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ponies/destroy.js.erb
$('.delete_pony').bind('ajax:success', function() {
        $(this).closest('tr').fadeOut();
});  

app/views/ponies/edit.html.erb
<h1>Editing Pony</h1>

<%= render 'form', pony: @pony %>

<%= link_to 'Show', @pony %> |
<%= link_to 'Back', ponies_path %>

app/views/ponies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ponies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profession</th>
      <th>Cutie mark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ponies.each do |pony| %>
      <tr>
        <td><%= pony.name %></td>
        <td><%= pony.profession %></td>
        <td><%= pony.cutie_mark %></td>
        <td><%= link_to 'Show', pony %></td>
        <td><%= link_to 'Edit', edit_pony_path(pony) %></td>
        <td><%= link_to 'Destroy', pony, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'delete_pony' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pony', new_pony_path %>

app/views/ponies/new.html.erb
<h1>New Pony</h1>

<%= render 'form', pony: @pony %>

<%= link_to 'Back', ponies_path %>

app/views/ponies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pony.name %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @pony.profession %>
</p>

<p>
  <strong>Cutie mark:</strong>
  <%= @pony.cutie_mark %>
</p>

<%= link_to 'Edit', edit_pony_path(@pony) %> |
<%= link_to 'Back', ponies_path %>